<?php

namespace atn\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserClassRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserClassRoomRepository extends EntityRepository
{
}
